data:
  seed: 42
  cnn_features_setting:
    frontend_algorithm: ["mfcc"]   # ["mfcc"] or ["lfcc"] or ["mfcc", "lfcc"]
    use_spectrogram: False
    use_deltas: False 


checkpoint:
  paths: [ ]

model:
  name: "lcnn"
  parameters:
    input_channels: 1
    num_coefficients: 80
    dropout: 0.15
    use_spec_augment: True
    use_checkpoint: True
  optimizer:
    lr: 0.001


 